param(
  [string]$ApiBase = "http://62.171.185.105:18081",
  [string]$VersionName = "1.0.205",
  [int]$VersionCode = 205
)

$ErrorActionPreference = "Stop"

$Root = Split-Path -Parent $PSScriptRoot
$ToolRoot = Join-Path $Root "tools\android-release"
$JdkHome = Join-Path $ToolRoot "jdk-21"
$SdkRoot = Join-Path $ToolRoot "sdk"
$CmdlineRoot = Join-Path $SdkRoot "cmdline-tools\latest"
$AndroidRoot = Join-Path $Root "capacitor\android"
$CapacitorRoot = Join-Path $Root "capacitor"
$CapacitorConfig = Join-Path $Root "capacitor\capacitor.config.json"
$NativeConfig = Join-Path $Root "web-client\public\native-config.js"
$RuntimeConfig = Join-Path $Root "web-client\public\runtime-config.js"
$Manifest = Join-Path $Root "capacitor\android\app\src\main\AndroidManifest.xml"
$NetworkSecurity = Join-Path $Root "capacitor\android\app\src\main\res\xml\network_security_config.xml"
$OutDir = Join-Path $Root "dist"

if (-not (Test-Path (Join-Path $JdkHome "bin\java.exe")) -or -not (Test-Path (Join-Path $CmdlineRoot "bin\sdkmanager.bat"))) {
  & (Join-Path $PSScriptRoot "setup-android-release-tools.ps1")
}

$env:JAVA_HOME = $JdkHome
$env:ANDROID_HOME = $SdkRoot
$env:ANDROID_SDK_ROOT = $SdkRoot
$env:Path = "$JdkHome\bin;$CmdlineRoot\bin;$SdkRoot\platform-tools;$env:Path"
$env:ANDROID_VERSION_CODE = [string]$VersionCode
$env:ANDROID_VERSION_NAME = $VersionName

$ApiBase = ([string]$ApiBase).Trim().TrimEnd("/")
if (-not $ApiBase.StartsWith("http://") -and -not $ApiBase.StartsWith("https://")) {
  throw "ApiBase must start with http:// or https://."
}

$OriginalNativeConfig = if (Test-Path $NativeConfig) { Get-Content -LiteralPath $NativeConfig -Raw } else { $null }
$OriginalRuntimeConfig = if (Test-Path $RuntimeConfig) { Get-Content -LiteralPath $RuntimeConfig -Raw } else { $null }
$OriginalCapacitorConfig = Get-Content -LiteralPath $CapacitorConfig -Raw
$OriginalManifest = Get-Content -LiteralPath $Manifest -Raw
$OriginalNetworkSecurity = Get-Content -LiteralPath $NetworkSecurity -Raw

try {
  $ApiBaseJson = ConvertTo-Json $ApiBase -Compress
  @(
    "// Auto-generated by scripts/build-android-fast-apk.ps1.",
    "// Sideload APK build. Store builds should use HTTPS and StrictStoreRelease.",
    "window.__DURAK_API_BASE__ = $ApiBaseJson;"
  ) | Set-Content -LiteralPath $NativeConfig -Encoding ASCII

  @(
    "// Auto-generated by scripts/build-android-fast-apk.ps1.",
    "window.__APP_ENV__ = `"production`";",
    "window.__PUBLIC_APP_URL__ = $ApiBaseJson;",
    "window.__ADMOB_ANDROID_APP_ID__ = `"`";",
    "window.__ADMOB_REWARDED_ANDROID_ID__ = `"`";",
    "window.__ADMOB_IOS_APP_ID__ = `"`";",
    "window.__ADMOB_REWARDED_IOS_ID__ = `"`";",
    "window.__ADMOB_REWARDED_ID__ = `"`";",
    "window.__ADMOB_SSV_CALLBACK_URL__ = (window.__PUBLIC_APP_URL__ || '') + '/api/admob/ssv';"
  ) | Set-Content -LiteralPath $RuntimeConfig -Encoding ASCII

  $capConfig = Get-Content -LiteralPath $CapacitorConfig -Raw | ConvertFrom-Json
  if (-not $capConfig.server) {
    $capConfig | Add-Member -MemberType NoteProperty -Name server -Value ([pscustomobject]@{})
  }
  $usesHttp = $ApiBase.StartsWith("http://")
  $capConfig.server.cleartext = $usesHttp
  $capConfig.server.androidScheme = if ($usesHttp) { "http" } else { "https" }
  $capConfig.server.iosScheme = if ($usesHttp) { "http" } else { "https" }
  $capConfig | ConvertTo-Json -Depth 20 | Set-Content -LiteralPath $CapacitorConfig -Encoding ASCII

  if ($ApiBase.StartsWith("http://")) {
    (Get-Content -LiteralPath $Manifest -Raw).Replace('android:usesCleartextTraffic="false"', 'android:usesCleartextTraffic="true"') |
      Set-Content -LiteralPath $Manifest -Encoding UTF8
    (Get-Content -LiteralPath $NetworkSecurity -Raw).Replace('cleartextTrafficPermitted="false"', 'cleartextTrafficPermitted="true"') |
      Set-Content -LiteralPath $NetworkSecurity -Encoding UTF8
  }

  Push-Location $CapacitorRoot
  try {
    & npx.cmd cap sync android
    if ($LASTEXITCODE -ne 0) { throw "Capacitor sync failed." }
  } finally {
    Pop-Location
  }

  Push-Location $AndroidRoot
  try {
    & .\gradlew.bat --stop | Out-Host
    & .\gradlew.bat assembleRelease "-PdurakVersionCode=$VersionCode" "-PdurakVersionName=$VersionName"
    if ($LASTEXITCODE -ne 0) { throw "Gradle assembleRelease failed." }
  } finally {
    Pop-Location
  }

  $apk = Join-Path $AndroidRoot "app\build\outputs\apk\release\app-release.apk"
  if (-not (Test-Path $apk)) { throw "APK file was not created." }
  New-Item -ItemType Directory -Force -Path $OutDir | Out-Null
  $target = Join-Path $OutDir ("DurakImperia-v{0}-apk-site-parity-release.apk" -f $VersionCode)
  Copy-Item -LiteralPath $apk -Destination $target -Force
  Write-Host "[android-fast-apk] APK ready: $target"
} finally {
  Set-Content -LiteralPath $CapacitorConfig -Value $OriginalCapacitorConfig -Encoding ASCII
  Set-Content -LiteralPath $Manifest -Value $OriginalManifest -Encoding UTF8
  Set-Content -LiteralPath $NetworkSecurity -Value $OriginalNetworkSecurity -Encoding UTF8
  if ($null -ne $OriginalNativeConfig) {
    Set-Content -LiteralPath $NativeConfig -Value $OriginalNativeConfig -Encoding ASCII
  } else {
    Remove-Item -LiteralPath $NativeConfig -Force -ErrorAction SilentlyContinue
  }
  if ($null -ne $OriginalRuntimeConfig) {
    Set-Content -LiteralPath $RuntimeConfig -Value $OriginalRuntimeConfig -Encoding ASCII
  } else {
    Remove-Item -LiteralPath $RuntimeConfig -Force -ErrorAction SilentlyContinue
  }
}
