param(
  [string]$ApiBase = "http://62.171.185.105:18081"
)

$ErrorActionPreference = "Stop"

$Root = Split-Path -Parent $PSScriptRoot
$ToolRoot = Join-Path $Root "tools\android-release"
$JdkHome = Join-Path $ToolRoot "jdk-21"
$SdkRoot = Join-Path $ToolRoot "sdk"
$CmdlineRoot = Join-Path $SdkRoot "cmdline-tools\latest"
$AndroidRoot = Join-Path $Root "capacitor\android"
$CapacitorConfig = Join-Path $Root "capacitor\capacitor.config.json"
$NativeConfig = Join-Path $Root "web-client\public\native-config.js"

if (-not (Test-Path (Join-Path $JdkHome "bin\java.exe")) -or -not (Test-Path (Join-Path $CmdlineRoot "bin\sdkmanager.bat"))) {
  & (Join-Path $PSScriptRoot "setup-android-release-tools.ps1")
}

$env:JAVA_HOME = $JdkHome
$env:ANDROID_HOME = $SdkRoot
$env:ANDROID_SDK_ROOT = $SdkRoot
$env:Path = "$JdkHome\bin;$CmdlineRoot\bin;$SdkRoot\platform-tools;$env:Path"

$ApiBase = ([string]$ApiBase).Trim().TrimEnd("/")
if (-not $ApiBase.StartsWith("http://") -and -not $ApiBase.StartsWith("https://")) {
  throw "Test APK requires ApiBase to start with http:// or https://."
}

$OriginalNativeConfig = $null
$HadNativeConfig = Test-Path $NativeConfig
if ($HadNativeConfig) {
  $OriginalNativeConfig = Get-Content -LiteralPath $NativeConfig -Raw
}
$OriginalCapacitorConfig = Get-Content -LiteralPath $CapacitorConfig -Raw

try {
  $ApiBaseJson = ConvertTo-Json $ApiBase -Compress
  @(
    "// Auto-generated by scripts/build-android-test-apk.ps1.",
    "// Test APK only. Store builds must use scripts/build-android-release.ps1 -StrictStoreRelease.",
    "window.__DURAK_API_BASE__ = $ApiBaseJson;"
  ) | Set-Content -LiteralPath $NativeConfig -Encoding ASCII

  $capConfig = Get-Content -LiteralPath $CapacitorConfig -Raw | ConvertFrom-Json
  if (-not $capConfig.server) {
    $capConfig | Add-Member -MemberType NoteProperty -Name server -Value ([pscustomobject]@{})
  }
  $capConfig.server.cleartext = $true
  $capConfig.server.androidScheme = "http"
  $capConfig.server.iosScheme = "http"
  $capConfig | ConvertTo-Json -Depth 20 | Set-Content -LiteralPath $CapacitorConfig -Encoding ASCII

  Push-Location (Join-Path $Root "capacitor")
  try {
    & npx cap sync android
    if ($LASTEXITCODE -ne 0) { throw "Capacitor sync failed." }
  } finally {
    Pop-Location
  }
} finally {
  Set-Content -LiteralPath $CapacitorConfig -Value $OriginalCapacitorConfig -Encoding ASCII
  if ($HadNativeConfig) {
    Set-Content -LiteralPath $NativeConfig -Value $OriginalNativeConfig -Encoding ASCII
  } else {
    Remove-Item -LiteralPath $NativeConfig -Force -ErrorAction SilentlyContinue
  }
}

Push-Location $AndroidRoot
try {
  & .\gradlew.bat --stop | Out-Host
  & .\gradlew.bat assembleDebug
  if ($LASTEXITCODE -ne 0) { throw "Gradle assembleDebug failed." }
} finally {
  Pop-Location
}

$apk = Join-Path $AndroidRoot "app\build\outputs\apk\debug\app-debug.apk"
if (-not (Test-Path $apk)) { throw "APK file was not created." }
Write-Host "[android-test-apk] APK ready: $apk"
